#!/usr/bin/env bash
# Bash script to Install nginx web server with custom header

sudo apt-get update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
header="\\\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "38i $header" /etc/nginx/sites-available/default
sudo service nginx restart
