#!/usr/bin/env bash
# Install and configure HAproxy

# Update Packages
apt-get -y update
apt-get -y upgrade

# Add Haproxy PPA
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.5
app-get -y update

# Install Haproxy
apt-get -y install haproxy=2.5.\*

# Configure Haproxy
config="\ \\\nfrontend balancer\n\tbind *:80\n\tmode http\n\tdefault_backend lb-backends\n\tbalance roundrobin\n\tserver 139248-web-01 100.25.35.29:80 check\n\tserver 139248-web-02 100.25.223.13:80 check
"
cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo $config >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
